package com.sachin_singh_dighan.newsapp

object AppConstant {

    //for main screen
    const val TOP_HEADLINES = "Top Headlines"
    const val NEWS_SOURCES = "News Sources"
    const val COUNTRIES = "Countries"
    const val LANGUAGES = "Languages"
    const val SEARCH = "Search"

    //for network service
    const val API_KEY = "5e59e08053df4d13a5d4ff6fb1b228d0"
    const val COUNTRY = "us"

    //Country name with code

    const val UNITED_ARAB_EMIRATES = "United Arab Emirates"
    const val UNITED_ARAB_EMIRATES_CODE = "ae"
    const val ARGENTINA = "Argentina"
    const val ARGENTINA_CODE = "ar"
    const val AUSTRIA = "Austria"
    const val AUSTRIA_CODE = "at"
    const val AUSTRALIA = "Australia"
    const val AUSTRALIA_CODE = "au"
    const val BELGIUM = "Belgium"
    const val BELGIUM_CODE = "be"
    const val BULGARIA = "Bulgaria"
    const val BULGARIA_CODE = "bg"
    const val BRAZIL = "Brazil"
    const val BRAZIL_CODE = "br"
    const val CANADA = "Canada"
    const val CANADA_CODE = "ca"
    const val SWITZERLAND = "Switzerland"
    const val SWITZERLAND_CODE = "ch"
    const val CHINA = "China"
    const val CHINA_CODE = "cn"
    const val COLOMBIA = "Colombia"
    const val COLOMBIA_CODE = "co"
    const val CUBA = "Cuba"
    const val CUBA_CODE = "cu"
    const val CZECH_REPUBLIC = "Czech Republic"
    const val CZECH_REPUBLIC_CODE = "cz"
    const val GERMANY = "Germany"
    const val GERMANY_CODE = "de"
    const val EGYPT = "Egypt"
    const val EGYPT_CODE = "eg"
    const val FRANCE = "France"
    const val FRANCE_CODE = "fr"
    const val UNITED_KINGDOM = "United Kingdom"
    const val UNITED_KINGDOM_CODE = "gb"
    const val GREECE = "Greece"
    const val GREECE_CODE = "gr"
    const val HONG_KONG = "Hong Kong"
    const val HONG_KONG_CODE = "hk"
    const val HUNGARY = "Hungary"
    const val HUNGARY_CODE = "hu"
    const val INDONESIA = "Indonesia"
    const val INDONESIA_CODE = "id"
    const val IRELAND = "Ireland"
    const val IRELAND_CODE = "ie"
    const val ISRAEL = "Israel"
    const val ISRAEL_CODE = "il"
    const val INDIA = "India"
    const val INDIA_CODE = "in"
    const val ITALY = "Italy"
    const val ITALY_CODE = "it"
    const val JAPAN = "Japan"
    const val JAPAN_CODE = "jp"
    const val KOREA_REPUBLIC = "Korea, Republic"
    const val KOREA_REPUBLIC_CODE = "kr"
    const val LITHUANIA = "Lithuania"
    const val LITHUANIA_CODE = "lt"
    const val LATVIA = "Latvia"
    const val LATVIA_CODE = "lv"
    const val MOROCCO = "Morocco"
    const val MOROCCO_CODE = "ma"
    const val MEXICO = "Mexico"
    const val MEXICO_CODE = "mx"
    const val MALAYSIA = "Malaysia"
    const val MALAYSIA_CODE = "my"
    const val NIGERIA = "Nigeria"
    const val NIGERIA_CODE = "ng"
    const val NETHERLANDS = "Netherlands"
    const val NETHERLANDS_CODE = "nl"
    const val NORWAY = "Norway"
    const val NORWAY_CODE = "no"
    const val NEW_ZEALAND = "New Zealand"
    const val NEW_ZEALAND_CODE = "nz"
    const val PHILIPPINES = "Philippines"
    const val PHILIPPINES_CODE = "ph"
    const val POLAND = "Poland"
    const val POLAND_CODE = "pl"
    const val PORTUGAL = "Portugal"
    const val PORTUGAL_CODE = "pt"
    const val ROMANIA = "Romania"
    const val ROMANIA_CODE = "ro"
    const val SERBIA = "Serbia"
    const val SERBIA_CODE = "rs"
    const val RUSSIAN_FEDERATION = "Russian Federation"
    const val RUSSIAN_FEDERATION_CODE = "ru"
    const val SAUDI_ARABIA = "Saudi Arabia"
    const val SAUDI_ARABIA_CODE = "sa"
    const val SWEDEN = "Sweden"
    const val SWEDEN_CODE = "se"
    const val SINGAPORE = "Singapore"
    const val SINGAPORE_CODE = "sg"
    const val SLOVENIA = "Slovenia"
    const val SLOVENIA_CODE = "si"
    const val SLOVAKIA_SLOVAK_REPUBLIC = "Slovakia (Slovak Republic)"
    const val SLOVAKIA_SLOVAK_REPUBLIC_CODE = "sk"
    const val THAILAND = "Thailand"
    const val THAILAND_CODE = "th"
    const val TURKEY = "Turkey"
    const val TURKEY_CODE = "tr"
    const val TAIWAN = "Taiwan"
    const val TAIWAN_CODE = "tw"
    const val UKRAINE = "Ukraine"
    const val UKRAINE_CODE = "ua"
    const val UNITED_STATES = "United States"
    const val UNITED_STATES_CODE = "us"
    const val VENEZUELA = "Venezuela"
    const val VENEZUELA_CODE = "ve"
    const val SOUTH_AFRICA = "South Africa"
    const val SOUTH_AFRICA_CODE = "za"


    //Languages
    const val ARABIC = "Arabic"
    const val ARABIC_CODE = "ar"
    const val GERMAN = "German"
    const val GERMAN_CODE = "de"
    const val ENGLISH = "English"
    const val ENGLISH_CODE = "en"
    const val SPANISH = "Spanish"
    const val SPANISH_CODE = "es"
    const val FRENCH = "French"
    const val FRENCH_CODE = "fr"
    const val HEBREW = "Hebrew"
    const val HEBREW_CODE = "he"
    const val ITALIAN = "Italian"
    const val ITALIAN_CODE = "it"
    const val DUTCH = "Dutch"
    const val DUTCH_CODE = "nl"
    const val NORWEGIAN = "Norwegian"
    const val NORWEGIAN_CODE = "no"
    const val PORTUGUESE = "Portuguese"
    const val PORTUGUESE_CODE = "pt"
    const val RUSSIAN = "Russian"
    const val RUSSIAN_CODE = "ru"
    const val SWEDISH = "Swedish"
    const val SWEDISH_CODE = "sv"
    const val UDMURT = "Udmurt"
    const val UDMURT_CODE = "ud"
    const val CHINESE = "Chinese"
    const val CHINESE_CODE = "zh"



}